# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 834a8a036f9197452c4e1bb0e16a51121e5273796eacc470fea74815ad615dc94c980380eab09a0663607881a76c8a2c02f724154805f9ba0d07d4c60c3d1a10

test:
  secret_key_base: f32dec8f610f503175e42ebcc5b415221099a7978df126d0090340a6b0052dd1b331c98cc618b010ddfa680b51305146d9a3590965ff423e3a8e0d148a02c7a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
